### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by kof** [jsstyles/jss#16]
- [x] for @media
- [x]  keyframes
```css
@-webkit-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}

@keyframes identifier {
  0% { top: 0; left: 0; }
  30% { top: 50px; }
  68%, 72% { left: 50px; }
  100% { top: 100px; left: 100%; }
}
```
- [ ] same for cli
