### ISSUE TITLE
Incorrect class number if media query is used

### ISSUE THREAD

**Issue by sammkj** [jsstyles/jss#210]
See this:
![image](https://cloud.githubusercontent.com/assets/9153498/14569415/46a77aa8-0304-11e6-8ef8-8f90f540244d.png)

**Comment by kof** [comment]
Looks like a bug, do you want to send me a pr? Anything is welcome a test, a fix or even both!

**Comment by sammkj** [comment]
I will try to do it this weekend. But I'm not familiar with the codebase though. I might or might not find the solution.

**Comment by kof** [comment]
u still trying?) let me know on gitter if you need any help

**Comment by sammkj** [comment]
@kof , sorry I still have yet to find the culprit.

**Comment by AriaFallah** [comment]
@kof does this mean you can't use media queries with JSS?

**Comment by kof** [comment]
No, it seems like if you have more than one per sheet, the second one will not work. @sammkj let me know if I should take it, because it's a bad issue.

**Comment by AriaFallah** [comment]
@kof I think it should be fixed as soon as possible. It's one of the reasons for me why I might pick something else over JSS.

**Comment by kof** [comment]
I always try to give people a chance to contribute if they want to, your call @sammkj

**Comment by sammkj** [comment]
@kof, that would be great if you can take over.

**Comment by kof** [comment]
ok

**Comment by kof** [comment]
@sammkj @AriaFallah let me know if fix doesn't work for you.

**Comment by AlastairTaft** [comment]
I still seem to have this issue. I'm running jss version `3.11.0` and loading my styles with `react-jss` version `2.0.6`.

The following styles
```js
container: {
  height: '100%',
  paddingTop: 125,
  paddingBottom: 125,
  boxSizing: 'border-box',
  paddingBottom: 125,
  position: 'fixed',
  height: '100%',
  top: 0,
},
'@media (max-width: 992px)': {
  container: {
    width: '100%',
  },
},
'@media (min-width: 992px)': {
  container: {
    width: '30%',
  },
},
```
gets converted to the following stylesheet.

```css
@media (min-width: 992px) {
  .container--jss-0-80 {
    width: 30%;
  }
}
.container--jss-0-81 {
  height: 100%;
  padding-top: 125px;
  padding-bottom: 125px;
  box-sizing: border-box;
  position: fixed;
  top: 0;
}
@media (max-width: 992px) {
  .container--jss-0-81 {
    width: 100%;
  }
}
```
