### ISSUE TITLE
[jss-fallback] Deprecate pattern "Array == Fallback". Move to separated plugin

### ISSUE THREAD

**Issue by typical000** [jsstyles/jss#256]
During implementation of [jss-shorthand plugin](https://github.com/typical000/jss-shorthand) I have faced one big problem ([original discussion](https://github.com/jsstyles/jss/issues/225)):

In JSS core, fallback are realised by simple patternt "If value is array - is a fallback". For example:
```javascript
button: {
  background: [
    'red',
    'linear-gradient(bla-bla)'
  ]
}
```
and the output will be:
```css
button {
  background: red;
  background: linear-gradient(bla-bla);
}
```
It's (as for me) a bad and uncler solution and can create more and more problems when JSS with plugins will growth.

As a solution I think to write a plugin **jss-Fallback** that realises something like this:
```javascript
button: {
  background: 'linear-gradient(foo)',
  display: 'inline-block',
  fallback: {
    background: 'red',
    display: 'inline'
  }
}
```
And the output will be:
```css
button {
  background: red;
  background: linear-gradient(foo);
  display: inline;
  display: inline-block;
}
```

But there is a question how to do it. Due to JS objects syntax we can't have 2 keys with the same name. So as a simplest solution I see something like this:

1. jss-fallbacks parses 'fallbacks' object in every rule
```javascript
button: {
  background: 'linear-gradient(foo)',
  fallback: {
    background: 'red',
  }
}
```
2. If there are keys that exists outside 'fallbacks' object (for example 'background' with value 'red' inside 'fallbacks', and 'background' outside with linear-gradient) - it merges them together to an array:
```javascript
button: {
  background: ['red', 'linear-gradient(foo)'],
}
```
3. jss by itself converts this value to regular css fallback:
```css
button {
  background: red;
  background: linear-gradient(foo);
}
```

This solution doesn't need to change jss core and fallbacks as arrays are preserved as deprecated solution. Maybe anyone have better and elegant solution? :)
