### ISSUE TITLE
Alternative syntax for space and comma separated values

### ISSUE THREAD

**Issue by kof** [jsstyles/jss#264]
In order to enable effective default unit insertion for shorthand notation, a non-string based way of space and comma separated css values in js is needed.

```javascript
{
  button: {
    margin: [[5, 10]]
  }
}
```

compiles to

```css
.button-12345 {
  margin: 5px 10px;
}
```

```javascript
{
  button: {
    border: [
      [1, 'solid', 'red'],
      [1, 'solid', 'blue']
   ]
  }
}
```

compiles to

```css
.button-12345 {
  border: 1px solid red, 1px solid blue;
}
```

```javascript
{
  button: {
    border: [
      '1px solid red',
      '1px solid blue'
   ]
  }
}
```

compiles to

```css
.button-12345 {
  border: 1px solid red, 1px solid blue;
}
```
