### ISSUE TITLE
Generated CSS incorrect for @media blocks?

### ISSUE THREAD

**Issue by mihalik** [jsstyles/jss#40]
I noticed my media queries were not working after converting to jss and after a bit of digging, I noticed it was generating code like this:

```css
@media (max-width: 600px) {
  .facet_sidebar: {
    display: none;
  }
}
```

The extra colon after .facet_sidebar is the issue.  Looking at the code, there is an exception for @keyframe to not include a colon but not @media.  I don't think I'm familiar enough with CSS to know why this is in place so I'm filing a ticket rather than pull request.
