### ISSUE TITLE
Sibling selector support?

### ISSUE THREAD

**Issue by mesteiral** [jsstyles/jss#86]
Is it possible to express this CSS snippet as a JSS sheet? And without resorting to globals? If possible, it doesn't seem obvious.

```css
.switch { /* ... */ }
.switch__input { /* */  }
.switch__input:checked + .switch__toggle { /* */ }
.switch__input:checked + .switch__toggle:before { /* */ }
.switch__input:not(:checked) + .switch__toggle:before { /* */ }
```

Example DOM:

```html
<label class="switch">
  <input class="switch__input" type="checkbox">
  <div class="switch__toggle"></div>
</label>
```

My intent would be making the `switch__toggle` styling dependent only on view-related concerns (i.e. whether the sibling input is `:checked`), thus avoiding introducing new classes to reflect component state.

**Comment by serapath** [comment]
The way I'm doing these kind of things is, to maintain some kind of `UI STATE`. So "checking/unchecking" a checkbox might set some part of the `UI STATE` to true/false and some other components or parts of the app might "listen" for changes of the UI STATE and update themselves accordingly.

**Comment by mesteiral** [comment]
@serapath It's what I'm doing. The checked state comes from the view (JS). My concern in my concrete example is that `<div class="switch__toggle"></div>` feeds on its **sibling** to style itself, and this relies on a **sibling selector**, which I don't know how to express in JSS.

Sure, one can add classes (say, with `--checked` ending) either to `div.switch` or `div.switch__toggle` to express checked state on `.switch__toggle`, but given an existing, complex stylesheet which is  developed separately, it would be much simpler to just rely on sibling selectors.

**Comment by kof** [comment]
yes, you can use pseudo selectors within  named rules via  jss-nested plugin

**Comment by kof** [comment]
Its a nice example, it would be nice to have it in jss-examples repository

**Comment by alexndl** [comment]
Thank you for the pointer. I went ahead and tried it, only having success in my use case with `named: false`:

```js
window.styles = {
  '.switch__input': {
    '&:checked + .switch__toggle': {background: 'red'}
  },
  '.switch__toggle': {}
}
```
Stylesheet creation:

```js
jss.use(jssNested).createStyleSheet(window.styles, {named: false}).attach()
```
yields:

```css
.switch__input {}
.switch__input:checked + .switch__toggle {background: red;}
.switch__toggle {}
```

However:

```js
jss.use(jssNested).createStyleSheet(window.styles, {named: true}).attach()
```

yields:

```css
.jss-0-0 {}
.jss-0-0:checked + .switch__toggle {background: red;}
.jss-0-2 {}
```

I expected `.switch__toggle` to be renamed to `.jss-0-2` in the second declaration.

Would this behavior be out of scope?

**Comment by mesteiral** [comment]
Thank you for the pointer. I went ahead and tried it, only having success in my use case with `named: false`:

```js
window.styles = {
  '.switch__input': {
    '&:checked + .switch__toggle': {background: 'red'}
  },
  '.switch__toggle': {}
}
```
Stylesheet creation:

```js
jss.use(jssNested).createStyleSheet(window.styles, {named: false}).attach()
```
yields:

```css
.switch__input {}
.switch__input:checked + .switch__toggle {background: red;}
.switch__toggle {}
```

However:

```js
jss.use(jssNested).createStyleSheet(window.styles, {named: true}).attach()
```

yields:

```css
.jss-0-0 {}
.jss-0-0:checked + .switch__toggle {background: red;}
.jss-0-2 {}
```

I expected `.switch__toggle` to be renamed to `.jss-0-2` in the second declaration.

Would this behavior be out of scope?
